/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class less_haku_androidres_util_JNIUtil */

#ifndef _Included_less_haku_androidres_util_JNIUtil
#define _Included_less_haku_androidres_util_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     less_haku_androidres_util_JNIUtil
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_less_haku_androidres_util_JNIUtil_getStringFormC
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_less_haku_androidres_util_JNIUtil_getStringWithPara
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
